# Generated by Django 5.2.9 on 2026-07-03 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_review_unique_together_review_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_customer_review',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_guest_phone_review',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'customer')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_notified',
            field=models.BooleanField(default=False, help_text='True if a low stock alert has already been sent.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='review',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='phone_number',
        ),
    ]
